import { defineConfig } from "oxfmt";
import ultracite from "ultracite/oxfmt";

export default defineConfig({
  ...ultracite,
  // generated by release-it
  ignorePatterns: [...(ultracite.ignorePatterns ?? []), "CHANGELOG.md"],
});
