import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";
import tanstack from "ultracite/oxlint/tanstack";

const restrictImports = (files: string[], regex: string, message: string) => ({
  files,
  rules: {
    "no-restricted-imports": ["error", { patterns: [{ message, regex }] }],
  },
});

const FSD_MESSAGE =
  "FSD: import only lower layers, through their public index.ts (docs/architecture.md §3)";

const FSD_RULES = [
  [["shared"], "^@/(entities|features|widgets|pages|app)(/|$)"],
  [["entities"], "^@/(entities|features|widgets|pages|app)(/|$)"],
  [["features"], "^@/(features|widgets|pages|app)(/|$)|^@/entities/[^/]+/."],
  [["widgets"], "^@/(widgets|pages|app)(/|$)|^@/(entities|features)/[^/]+/."],
  [["pages"], "^@/(pages|app)(/|$)|^@/(entities|features|widgets)/[^/]+/."],
  [
    ["app", "routes", "entrypoints"],
    "^@/(entities|features|widgets|pages)/[^/]+/.",
  ],
] as const;

const fsdOverrides = (srcDir: string, extraRegex = "", message = FSD_MESSAGE) =>
  FSD_RULES.map(([dirs, regex]) =>
    restrictImports(
      dirs.map((dir) => `${srcDir}/${dir}/**`),
      `${regex}${extraRegex}`,
      message
    )
  );

export default defineConfig({
  extends: [core, react, tanstack],
  ignorePatterns: [
    ...core.ignorePatterns,
    // Vendored shadcn output (regenerated by `shadcn add`) and Alchemy-generated env types.
    "packages/ui/src/components/**",
    "packages/ui/src/hooks/**",
    "apps/web/cloudflare-env.d.ts",
  ],
  overrides: [
    ...fsdOverrides("apps/web/src"),
    restrictImports(
      ["packages/capture/src/domain/**"],
      "(^|/)(application|infrastructure)(/|$)|^(@zam/|drizzle-orm|better-auth|zod)",
      "Clean Architecture: domain imports nothing outside src/domain (docs/architecture.md §3)"
    ),
    restrictImports(
      ["packages/capture/src/application/**"],
      "(^|/)infrastructure(/|$)|^(@zam/|drizzle-orm|better-auth)",
      "Clean Architecture: application depends only on domain (docs/architecture.md §3)"
    ),
    restrictImports(
      ["packages/capture/src/application/queries/**"],
      "(^|/)infrastructure(/|$)|^(@zam/|drizzle-orm|better-auth)|/domain/bug-report(-repository)?$|(^|/)commands(/|$)",
      "CQRS: queries read through BugReportReadModel, never the aggregate or commands (docs/architecture.md §5)"
    ),
    restrictImports(
      ["packages/api/src/**"],
      "^@zam/capture/infrastructure(/|$)|^@zam/db(/|$)",
      "Adapters are wired only in the composition root apps/web/src/shared/api/server/services.ts (docs/architecture.md §3)"
    ),
    ...fsdOverrides(
      "apps/extension/src",
      "|^@zam/capture/(application|infrastructure)(/|$)|^@zam/(db|auth)(/|$)",
      "FSD + shared kernel: import lower layers via public index.ts; from @zam/capture only domain (docs/architecture.md §3)"
    ),
  ],
});
